import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { fileURLToPath } from "url";
import path from "path";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Resolve protocol package source directly (monorepo path alias)
const protocolSrc = path.join(__dirname, "..", "protocol", "src", "index.ts");

const postBuildPlugin = {
  name: "post-build",
  setup(build) {
    const BUILD_DIR = __dirname + "/";
    // Copy artifacts into server's client/ dir for auto-update distribution
    const SERVER_CLIENT_DIR = path.join(__dirname, "..", "server", "client") + path.sep;
    const SERVER_ROOT_DIR = path.join(__dirname, "..", "server") + path.sep;

    build.onEnd(async () => {
      const pkg = JSON.parse(fs.readFileSync("./package.json", "utf-8"));
      const VERSION = pkg.version;
      const BUILD = Date.now();

      // Stamp version + build into the bundle
      const mainJs = fs.readFileSync(BUILD_DIR + "main.js", "utf-8")
        .replaceAll("__IONSYNC_VERSION__", JSON.stringify(VERSION))
        .replaceAll("__IONSYNC_BUILD__", JSON.stringify(String(BUILD)));
      fs.writeFileSync(BUILD_DIR + "main.js", mainJs);

      // Sign main.js when a build secret is present. The private key never
      // enters the runtime image; the plugin pins the matching public key and
      // verifies before hot-reloading server-pushed code (updateSig / SECURITY.md
      // #4). Without a key the build is UNSIGNED and signed clients refuse to
      // auto-update — a safe, loud failure, never an RCE. Transport-independent:
      // it protects ws:// and wss:// alike, so it never forces TLS on anyone.
      let sig;
      const signKey = (process.env.IONSYNC_SIGN_KEY || "").trim();
      if (signKey) {
        try {
          const { signPluginBundle } = await import("../protocol/dist/index.js");
          sig = signPluginBundle(Buffer.from(mainJs, "utf-8"), signKey);
          console.log("[sign] main.js signed");
        } catch (e) {
          console.error("[sign] FAILED to sign (build will be UNSIGNED):", e);
        }
      } else {
        console.warn("[sign] IONSYNC_SIGN_KEY not set — build is UNSIGNED; signed clients will refuse auto-update.");
      }

      // Keep manifest.json version in sync
      const manifest = JSON.parse(fs.readFileSync("./manifest.json", "utf-8"));
      manifest.version = VERSION;
      fs.writeFileSync("./manifest.json", JSON.stringify(manifest, null, "\t"));

      // Update versions.json
      const versions = JSON.parse(fs.readFileSync("./versions.json", "utf-8"));
      versions[VERSION] = manifest.minAppVersion;
      fs.writeFileSync("./versions.json", JSON.stringify(versions, null, "\t"));

      // Write build_info.json (used by server version_check handler).
      // `build` MUST be a string: the plugin sends it as a string in
      // version_check and the server compares with !== — a numeric value here
      // would make every connect look like an update (reload loop).
      fs.writeFileSync(BUILD_DIR + "build_info.json", JSON.stringify({ version: VERSION, build: String(BUILD), ...(sig ? { sig } : {}) }));

      // Copy to server/client/ so the server can distribute the plugin for
      // auto-update. build_info.json MUST be in this list — without it the
      // server's version_check finds no build info and answers
      // needsUpdate:false forever, silently disabling auto-update.
      if (fs.existsSync(SERVER_CLIENT_DIR)) {
        for (const file of ["main.js", "styles.css", "manifest.json", "build_info.json"]) {
          if (fs.existsSync(BUILD_DIR + file)) {
            fs.copyFileSync(BUILD_DIR + file, SERVER_CLIENT_DIR + file);
          }
        }
        // Also sync server package.json version
        const serverPkgPath = path.join(SERVER_ROOT_DIR, "package.json");
        if (fs.existsSync(serverPkgPath)) {
          const serverPkg = JSON.parse(fs.readFileSync(serverPkgPath, "utf-8"));
          serverPkg.version = VERSION;
          fs.writeFileSync(serverPkgPath, JSON.stringify(serverPkg, null, "\t"));
        }
      }

      // Mirror manifest.json + versions.json to the repo ROOT. Obsidian's
      // community-plugin submission and BRAT both read manifest.json from the
      // repository root to discover the plugin id/version; this is a monorepo
      // (source lives in packages/plugin/), so copy them up to keep root in sync.
      const REPO_ROOT = path.join(__dirname, "..", "..") + path.sep;
      for (const file of ["manifest.json", "versions.json"]) {
        if (fs.existsSync(BUILD_DIR + file)) {
          fs.copyFileSync(BUILD_DIR + file, REPO_ROOT + file);
        }
      }

      // Copy to local Obsidian vault for dev convenience (optional path)
      const LOCAL_VAULT = process.env.OBSIDIAN_PLUGIN_DIR || "";
      if (LOCAL_VAULT && fs.existsSync(LOCAL_VAULT)) {
        for (const file of ["main.js", "styles.css", "manifest.json"]) {
          if (fs.existsSync(BUILD_DIR + file)) {
            fs.copyFileSync(BUILD_DIR + file, path.join(LOCAL_VAULT, file));
          }
        }
      }
    });
  },
};

// esbuild v0.17+ removed the `watch` option from build() — watch mode now
// requires context().watch().  Branch on prod/dev accordingly.
const buildOptions = {
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  alias: {
    "@ionsync/protocol": protocolSrc,
  },
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [postBuildPlugin],
};

if (prod) {
  esbuild.build(buildOptions).catch(() => process.exit(1));
} else {
  const ctx = await esbuild.context(buildOptions);
  await ctx.watch();
  console.log("Watching for changes…");
}
