import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import { fileURLToPath } from "url";
import path from "path";
import fs from "fs";
import crypto from "node:crypto";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Protocol source travels with the plugin in this standalone repo (it is a
// workspace package in the IonSync monorepo). Resolve the bare specifier to it.
const protocolSrc = path.join(__dirname, "src", "protocol", "index.ts");

const postBuildPlugin = {
	name: "post-build",
	setup(build) {
		const BUILD_DIR = __dirname + "/";
		build.onEnd(() => {
			const pkg = JSON.parse(fs.readFileSync("./manifest.json", "utf-8"));
			const VERSION = pkg.version;

			// Deterministic build id: sha256 of the pre-stamp bundle + version,
			// never wall-clock time, so a clean checkout of a given commit yields
			// byte-identical main.js (the community reviewer's rebuild matches the
			// released artifact). It still changes with source/version, so the
			// self-hosted server's version_check (a string !== comparison) keeps
			// detecting real updates.
			const rawBundle = fs.readFileSync(BUILD_DIR + "main.js", "utf-8");
			const BUILD = crypto
				.createHash("sha256")
				.update(rawBundle)
				.update("\0" + VERSION)
				.digest("hex")
				.slice(0, 16);

			const mainJs = rawBundle
				.replaceAll("__IONSYNC_VERSION__", JSON.stringify(VERSION))
				.replaceAll("__IONSYNC_BUILD__", JSON.stringify(String(BUILD)));
			fs.writeFileSync(BUILD_DIR + "main.js", mainJs);
		});
	},
};

const buildOptions = {
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	alias: {
		"@ionsync/protocol": protocolSrc,
	},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [postBuildPlugin],
};

if (prod) {
	esbuild.build(buildOptions).catch(() => process.exit(1));
} else {
	const ctx = await esbuild.context(buildOptions);
	await ctx.watch();
	console.log("Watching for changes…");
}
